# Generated by Django 2.0.1 on 2018-11-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
