# Generated by Django 2.0.1 on 2018-12-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181128_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.IntegerField(default=2272, primary_key=True, serialize=False, unique=True),
        ),
    ]
